import { CompanyResponse } from "@/app/interfaces";

const sampleCompanies: CompanyResponse[] = [
    {
        id: "1",
        name: "Allianze",
        logo: "/logo/1.jpg",
        description: "Leading provider of comprehensive life and accident insurance solutions with over 20 years of experience in the Lao market. Committed to protecting families and individuals with reliable coverage and exceptional customer service.",
        available_insurances: ["life", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "2",
        name: "AIA",
        logo: "/logo/2.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "3",
        name: "Phongsavanh",
        logo: "/logo/3.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "4",
        name: "BSH",
        logo: "/logo/4.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "5",
        name: "Insee",
        logo: "/logo/5.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "6",
        name: "HPC",
        logo: "/logo/6.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "7",
        name: "Zhong Ji",
        logo: "/logo/7.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "8",
        name: "Laothepchalern",
        logo: "/logo/8.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "9",
        name: "Kungthep",
        logo: "/logo/9.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "10",
        name: "Lao chine pacific",
        logo: "/logo/10.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "11",
        name: "Lao vivat",
        logo: "/logo/11.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "12",
        name: "LVI",
        logo: "/logo/12.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "13",
        name: "MSIG",
        logo: "/logo/13.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "14",
        name: "Lanxang",
        logo: "/logo/14.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "15",
        name: "Prudential",
        logo: "/logo/15.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "16",
        name: "Muanfthai",
        logo: "/logo/16.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "17",
        name: "Toyota",
        logo: "/logo/17.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "18",
        name: "TK",
        logo: "/logo/17.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "19",
        name: "Thipphaya",
        logo: "/logo/19.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "20",
        name: "VTI",
        logo: "/logo/20.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "21",
        name: "Sokxay",
        logo: "/logo/21.jpg",
        description: "Trusted insurance partner specializing in health and accident protection. We offer flexible insurance plans tailored to your needs, backed by a nationwide network of healthcare providers and quick claim processing.",
        available_insurances: ["health", "accident"],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export const getCompanyList: () => Promise<CompanyResponse[]> = () => new Promise((resolve) => {
    resolve(sampleCompanies);
});

export const getCompany = async (id: string): Promise<CompanyResponse | undefined> => {
    return new Promise((resolve) => {
        resolve(sampleCompanies.find((company) => company.id === id));
    });
}